#!/bin/sh
# This script changes to the pokemonsay installation directory,
# runs the main script for running the pokemonthink, and changes
# back to the previous directory.
cd /usr/share/pokemonsay
./pokemonthink.sh $@
cd - >/dev/null
